## Info before preprocesing

In [1]:
import pickle
import numpy as np
import sys
sys.path.append('../ml/BERT')

from Vectorisation import Vectorisation
from Config import Config
import masking

In [2]:
with open("../../data/ml4science_data.pkl", "rb") as fp:
    dl = pickle.load(fp)

In [3]:
print(dl.keys())
dl["sequences"][0].keys()

dict_keys(['sequences', 'index', 'available_demographics'])


dict_keys(['path', 'length', 'learner_id', 'raw_sequence', 'raw_begin', 'raw_end', 'last_timestamp', 'permutation', 'gender', 'year', 'language', 'begin', 'end', 'break_sequence', 'sequence', 'label', '1hot-sequence', 'nobreak', 'nobreak-1hot-sequence', 'stratifier_column'])

In [4]:
for i in range(6):
    print(
        "begin {} - end {}: {}".format(
            dl["sequences"][0]["begin"][i],
            dl["sequences"][0]["end"][i],
            dl["sequences"][0]["sequence"][i],
        )
    )

begin 0 - end 7.889: [0, 0, 0, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3440621047581669]
begin 7.889 - end 83.03: [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.9999999999999999, 0.0]
begin 83.03 - end 86.28: [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.14174189890531658]
begin 86.28 - end 86.33: [0.0, 0.0, 0.0, 1.0, 0.006079027355622759, 0.0, 0.0, 0.0, 0.0, 0.0]
begin 87.278 - end 90.562: [0.0, 0.0, 0.0, 1.0, 0.3992705167173245, 0.0, 0.0, 0.0, 0.0, 0.0]
begin 90.562 - end 99.597: [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3940424789567799]


In [5]:
student_seq = [len(dl["sequences"][i]["sequence"]) for i in range(len(dl["sequences"]))]

print(np.mean(student_seq), "+-", np.std(student_seq))
print(np.min(student_seq))
print(np.max(student_seq))

100.31496062992126 +- 102.75095652848267
13
819


In [6]:
config = Config()
vec = Vectorisation(config=config)

encoded = vec.encode_dict(dl)

## Testing for Vectorisation with dict
### Encoding

In [7]:
stud0 = dl["sequences"][0]
for i in range(20):
    print(
        f"begin {stud0['begin'][i]} - end {stud0['end'][i]}: \t {stud0['sequence'][i]} \t -> {encoded[0][i]}"
    )

begin 0 - end 7.889: 	 [0, 0, 0, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3440621047581669] 	 -> 26
begin 7.889 - end 83.03: 	 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.9999999999999999, 0.0] 	 -> 2
begin 83.03 - end 86.28: 	 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.14174189890531658] 	 -> 26
begin 86.28 - end 86.33: 	 [0.0, 0.0, 0.0, 1.0, 0.006079027355622759, 0.0, 0.0, 0.0, 0.0, 0.0] 	 -> 21
begin 87.278 - end 90.562: 	 [0.0, 0.0, 0.0, 1.0, 0.3992705167173245, 0.0, 0.0, 0.0, 0.0, 0.0] 	 -> 21
begin 90.562 - end 99.597: 	 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3940424789567799] 	 -> 26
begin 99.597 - end 100.32: 	 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.1239499399965717, 0.0, 0.0, 0.0] 	 -> 23
begin 101.267 - end 107.071: 	 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0772414527355239, 0.0] 	 -> 25
begin 108.989 - end 114.653: 	 [0.0, 0.0, 0.0, 1.0, 0.6886322188449855, 0.0, 0.0, 0.0, 0.0, 0.0] 	 -> 21
begin 115.424 - end 115.935: 	 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.08760500600034259, 0.0,

In [8]:
print(encoded[0])

[26  2 26 21 21 26 23 25 21 23  2 21 26 21 21 26 21 25  3  8  3  3  3  3
  3  3  3  3  7  8  4  2  8  3 16 20 21 26 21 23 21  3  8  7  8  3  5  8
  4  8  2  8  3  8 10  9 10  9  9 15 20 11  9 14 13 11  9 14 13 14 10 11
  9  9 13 14 13 14 11  9 10 14 13 10 11  9 14  9 14 15 20 15 15 17 20  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

### Decoding

In [9]:
decoded = vec.decode_dict(encoded)

stud0 = dl["sequences"][0]
for i in range(20):
    print(
        f"begin {stud0['begin'][i]} - end {stud0['end'][i]}: \t {stud0['sequence'][i]} \t -> {encoded[0][i]} -> \t {decoded['sequences'][0]['sequence'][i]}"
    )

begin 0 - end 7.889: 	 [0, 0, 0, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3440621047581669] 	 -> 26 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
begin 7.889 - end 83.03: 	 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.9999999999999999, 0.0] 	 -> 2 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0]
begin 83.03 - end 86.28: 	 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.14174189890531658] 	 -> 26 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
begin 86.28 - end 86.33: 	 [0.0, 0.0, 0.0, 1.0, 0.006079027355622759, 0.0, 0.0, 0.0, 0.0, 0.0] 	 -> 21 -> 	 [0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
begin 87.278 - end 90.562: 	 [0.0, 0.0, 0.0, 1.0, 0.3992705167173245, 0.0, 0.0, 0.0, 0.0, 0.0] 	 -> 21 -> 	 [0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
begin 90.562 - end 99.597: 	 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3940424789567799] 	 -> 26 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
begin 99.597 - end 100.32: 	 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.1239499399965717, 0.0, 0.0, 0.0] 	 -> 23 -> 	 [0, 0, 0, 1, 0, 0, 1, 0, 0, 0]
begin 101.267 - end 107.071: 	 [0.0, 0.0, 0.0

## Testing for Vectorisation without dict
### Encoding

In [10]:
stud1 = [
    [1, 0, 0, 0, 10, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 14, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 10],
    [0, 0, 0, 1, 11, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 12, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 13],
]

stud2 = [
    [0, 0, 0, 1, 0, 0, 0, 0, 15, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 16, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 10],
    [0, 0, 0, 1, 13, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 12, 0, 0, 0, 0, 0],
]

stud3 = [
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 10], 
    [0, 0, 0, 1, 0, 0, 0, 0, 17, 0]
]

studs = [stud1, stud2, stud3]
type(studs)

list

In [11]:
config2 = Config(MAX_LEN=6)
vec2 = Vectorisation(config=config2)

# without defining breaks
enc_no_sep = vec2.encode(studs)
print(enc_no_sep)

[[ 3  7  8 21 21 26]
 [25 25 26 21 21  0]
 [26 25  0  0  0  0]]


In [12]:
# with artificial breaks
seps_art = np.array(
    [[0, 1, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0]], dtype=bool
)
enc_sep_art = vec2.encode(studs, seps_art)
print(enc_sep_art)

[[ 3  2  8 21 21 26]
 [ 2  2 26 21 21  0]
 [26  2  0  0  0  0]]


In [13]:
# with sequence encoded breaks
seps_seq = vec2.sep_from_seq(studs)

enc_sep_sep = vec2.encode(studs, seps_seq)
print(enc_sep_sep)

[[ 3  7  8 21 21 26]
 [25  2 26 21 21  0]
 [26  2  0  0  0  0]]


### Decoding

In [14]:
dec = vec2.decode(enc_sep_sep)

for i in range(len(dec)):
    for j in range(len(dec[i])):
        print(f"{studs[i][j]} \t -> \t {enc_sep_sep[i][j]} \t -> \t {dec[i][j]}")
    print("\n")

[1, 0, 0, 0, 10, 0, 0, 0, 0, 0] 	 -> 	 3 	 -> 	 [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 14, 0] 	 -> 	 7 	 -> 	 [1, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 10] 	 -> 	 8 	 -> 	 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[0, 0, 0, 1, 11, 0, 0, 0, 0, 0] 	 -> 	 21 	 -> 	 [0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 12, 0, 0, 0, 0, 0] 	 -> 	 21 	 -> 	 [0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 13] 	 -> 	 26 	 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1]


[0, 0, 0, 1, 0, 0, 0, 0, 15, 0] 	 -> 	 25 	 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 16, 0] 	 -> 	 2 	 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 10] 	 -> 	 26 	 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
[0, 0, 0, 1, 13, 0, 0, 0, 0, 0] 	 -> 	 21 	 -> 	 [0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 12, 0, 0, 0, 0, 0] 	 -> 	 21 	 -> 	 [0, 0, 0, 1, 1, 0, 0, 0, 0, 0]


[0, 0, 0, 1, 0, 0, 0, 0, 0, 10] 	 -> 	 26 	 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
[0, 0, 0, 1, 0, 0, 0, 0, 17, 0] 	 -> 	 2

### Decoding with time information

In [15]:
dec = vec2.decode(enc_sep_sep)
dec = vec2.add_time_info(dec, studs)

for i in range(len(dec)):
    for j in range(len(dec[i])):
        print(f"{studs[i][j]} \t -> \t {enc_sep_sep[i][j]} \t -> \t {dec[i][j]}")
    print("\n")

[1, 0, 0, 0, 10, 0, 0, 0, 0, 0] 	 -> 	 3 	 -> 	 [1, 0, 0, 0, 10, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 14, 0] 	 -> 	 7 	 -> 	 [1, 0, 0, 0, 0, 0, 0, 0, 14, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 10] 	 -> 	 8 	 -> 	 [1, 0, 0, 0, 0, 0, 0, 0, 0, 10]
[0, 0, 0, 1, 11, 0, 0, 0, 0, 0] 	 -> 	 21 	 -> 	 [0, 0, 0, 1, 11, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 12, 0, 0, 0, 0, 0] 	 -> 	 21 	 -> 	 [0, 0, 0, 1, 12, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 13] 	 -> 	 26 	 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 0, 13]


[0, 0, 0, 1, 0, 0, 0, 0, 15, 0] 	 -> 	 25 	 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 15, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 16, 0] 	 -> 	 2 	 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 16, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 10] 	 -> 	 26 	 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 0, 10]
[0, 0, 0, 1, 13, 0, 0, 0, 0, 0] 	 -> 	 21 	 -> 	 [0, 0, 0, 1, 13, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 12, 0, 0, 0, 0, 0] 	 -> 	 21 	 -> 	 [0, 0, 0, 1, 12, 0, 0, 0, 0, 0]


[0, 0, 0, 1, 0, 0, 0, 0, 0, 10] 	 -> 	 26 	 -> 	 [0, 0, 0, 1, 0, 0, 0, 0, 0, 10]
[0, 0, 0, 1, 0, 0, 0, 0, 17,

# Masking Test

In [16]:
encoded_masked, labels, weights = masking.mask_input_and_labels(encoded, config.TOKEN_DICT)

In [17]:
print("Original: ", encoded[0])
print("Masked: ", encoded_masked[0])

Original:  [26  2 26 21 21 26 23 25 21 23  2 21 26 21 21 26 21 25  3  8  3  3  3  3
  3  3  3  3  7  8  4  2  8  3 16 20 21 26 21 23 21  3  8  7  8  3  5  8
  4  8  2  8  3  8 10  9 10  9  9 15 20 11  9 14 13 11  9 14 13 14 10 11
  9  9 13 14 13 14 11  9 10 14 13 10 11  9 14  9 14 15 20 15 15 17 20  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0 

In [18]:
percentage_ones = (
    np.count_nonzero(encoded_masked == 1, axis=1)
    / np.count_nonzero(encoded_masked, axis=1)
    * 100
)
print(percentage_ones)

print(
    "Total %:",
    percentage_ones.mean(),
    "+-",
    percentage_ones.std(),
    "\nExpected %:",
    0.15 * 0.8,
    "(0.15% * 0.8%)",
)
# Small % than expected cuz we don't mask SEP

[12.63157895 10.3626943  12.5        12.19512195 12.90322581 12.5
 12.74509804 13.33333333  0.         14.47368421 10.78431373 19.04761905
 12.58741259 10.95890411 15.09433962 11.36363636 11.62790698  6.06060606
  0.         12.5         8.49056604  3.57142857  7.01754386  4.21052632
  9.375      18.60465116  5.55555556  8.55614973 13.51351351 12.35955056
  8.33333333 10.71428571  9.85221675  3.7037037  12.02185792 16.41791045
  6.94444444 13.51351351 14.94252874 11.48325359 15.68627451 11.11111111
 14.58333333  6.25        8.46153846  8.69565217  7.89473684  0.
  5.         10.96938776  7.3089701   8.36653386  7.54716981  8.69565217
  0.         18.         10.2739726  16.66666667  5.88235294 12.16216216
 10.86956522 11.65048544 16.66666667 17.24137931 14.63414634  5.58659218
 13.88888889 13.79310345  9.77443609 10.11673152  0.         18.42105263
 11.85185185  6.52173913 12.82051282  6.66666667  8.84955752 13.79310345
 18.98734177  7.69230769 12.03703704 14.0625     10.25641026 16.66

In [19]:
# labels just correspond to the unmasked data
np.all(labels == encoded)

True

In [20]:
print(weights[0])  # has 1 where there is a 1 in the masked sequence (masked)
print(encoded_masked[0])

[0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.